package my.leetcode.qs;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class Q2156Test {
	
		@Test
	void t2() {
		int p;
		long h;
		Q2156 q;
		String s;
		assertEquals(1, 'a' - 96);
		assertEquals(26, 'z' - 96);
		q = new Q2156();
		h = q.hash("leetcode",1, 2, 7, 20);
		assertEquals(0, h);
		q = new Q2156();
		h = q.hash("fbxzaad",0, 3, 31, 100);
		assertEquals(32, h);

		q = new Q2156();
		h = q.hash("xmmhdakfursinye",0, 15, 96, 45);
		assertEquals(21, h);

		q = new Q2156();
		p = q.search("leetcode", 7, 20, 2, 0);
		assertEquals(1, p);

		q = new Q2156();
		p = q.search("fbxzaad", 31, 100, 3, 32);
		assertEquals(0, p);

		q = new Q2156();
		p = q.search("xmmhdakfursinye", 96, 45, 15,21);
		assertEquals(0, p);

	}


		@Test
	void t3() {
		int p,h;
		Q2156 q;
		String s;
		q = new Q2156();
		s = "kfedcbdngvlykqyrbvwbnaassgjifjxtawlafhcpjtpzfnbsqfasohevbbhkwmtnmixolfepkjmcbadqcljmsbonrngsgfqwzqiisbiwiqgtqtqddukgtjymbxzmtxrobuhkdxmdmqccrauzkrjisstznnkhupiandekzcchsrzwintkkzhvqomqmnbasynmvtxwydcvwoukqmgrpmgzqancuzapgncasxnbyznlrdvcbomdptjftgxdzeqzyavfdpseoxpvohpxtikyjfvskxyqbubgnseraxtrcrwjxloxymhqgaxwbbvzhjsbncqrlpdbiuakdjzjrbclhxgnjjyfrqyjchlsdrcwtdoktviqwjctlmzqemumgmjufcbixkfhzkugsvnkrrakccguybwhmuexiemqusltaaqrswsezccqzaputgaabrjdeihmkpzbojnusmhkwjdxvgiexwdkkazhhmlalgzvxgqgncfytrxuhkwhwcxhmlbvkhjcnyztepwnlpthozdqexvhxpvheopjrsjzkqrstczffkhkikelwydcbnghfiibeyabgegdgaqvasujmggltkvokmnsmontjzsmzoeeqenafvurbnbwqbizvaqxfgnoxasctfrwvqmoufvpajdkethlvbhbehxahcpcizocbchwfznhuqtblwepeqdhycrovqosmxxeeqaffjvvclmpcqdugndexexcykyusetuamymszlteobxkestwbzubpstbwrstuovlybycevedzgurqvlgkouvavcukccgixixsrndurvrkfegegnchbhockujlafxexlxhgysraviztkjymiqxrlldcixvfnzrpserrqycbfmesqbltywmandcqtluccbisfqzosbvedqhsxepdjevaasylvjmfpvyxqvclaalgxytiukyarojmzyovmiunkvqhkouhxxhbemavagrhteofpowvlpdunjjpwgcjibagfswrzwkgrwklppchvtukzncvoqorlsskyghkhrazwvyqqjfygmduhsfkrseddgmtdvlqeruxogmyttdqmdpmscspatkoifauivwjtbwisiiqztrllfqnjvbagrfylrpjudjmvwhdkhahyxlsfbkuuyofryfgblllzeacfiqqawridcbtqnroxwuqhyspqmwhxmjztqokofnkfvupcykszthicdgjbrgafpztktrcwtayoulnjaazigkinnpttghhyboiczvtswenshlmqyelnwhzqlswblqssiiynypfcxerlykpiyimkoodimdfdlzbwmlwflylcqwaflivqeonjswvowxgeoafmppodmfbvooodtnzgmhfnchenaaywqevklrpgajbmbxgiopofghlouhjfarjxlclcullsgyzhohowtragbkaebrvbkmxfxughlirtikheojbrrgxtqldfdnqxndzvfgajiltnqnuwavxbrvuiycsizunlglwnivpseyfwmgydmmpzhxkdtpuzpddacjmjhvncdoicedkimdgaqobdfagpggvjemstqbsshynyvhdyslgldvkapqgusmnuroqxcivjifkhrotomxodficktxmcytkbqitrlalpbtphowfgtzgfacabjodvivgykorvmxhzpqvskolkbfpbdgowlighossrlwiomgohfhgklmlnekniqfjmvvqvmimkeddfxnxwzzroospxvndynetghkgrakuslukqsrdtmjkblwrmwhzzojcwwogrjvnftdwwpoqcjqimvjbwgqgpeffjnwlzdyhkhwmvpwpcmjmdqneexqwcrvdxsfsnidwyflwxwngczklprhoazeeqwclrqvnicfvrtbqailbwrqxadxslouwdjycidupemdwhpkqekaxxprtdtmjficrhlvqidvgwkllaowyyajkxugqiztbpzvjqtpuyugkvdfcaczzruskvucsxtvroljnjojuzncatgnypbzwvilbajqqnjovqxcfunwwbxgshrjlajwveaswqegidfnedpxqdreddvawrpbllkcshlafnxyocbmwacytvgtoonlkukqhxwbfxcfnbgmrfcnkvtxmygiyjoyoljd";
		p = q.search(s, 71717, 94536, 1149,39999);
		assertEquals(936, p);
	}
	
		@Test
	void t4() {
		int p,h;
		Q2156 q;
		String s;
		q = new Q2156();
		s = "idmqbuxyodnfjqqkvbufbrbleswpxgjcsdmiipyulasthaiidlatjfjquzjwwigvtraqnpcsmkjtpktoscxpyrobesfoyxxmqvrbiaqhxgennfnsvjfobrxihlisswspqshucfjhumhpyxhqmonmuqwpfubazjolsafewrewkhsqksygeboxusjhittltndcgdftoxzfbcajfqlhtsscnsplcykicwjrvnlbknptxkmudwismybeugsreotxrafzwhykgodiyrfutqqmlncqhuakhwsitskoblancgyzzgytyfhbbauwdmndeooaxtkrwkhkpvksfmavpkoylimzrgchlxqhgeahhgubrsnbvsgczlhoivyfmsdtwvftwyjjhzufxbqwzovfvyibgmvgyigfxyywguciqwzylvqpazcdfjsjpgiokxsibwblsprmuxlcdevuxuisdxgxlehjdqnwfzduzrqfbdpraezgcmhzkklmpdrmvxjcukxtpnwqnoexuhhcegjceboickgfdyxcwunmfpmhppqcjwqkxoifiilwtwkhrueosqfezdrtttukuibwjvuozgulqzehqdmvacfzbrhdlpmslyyhxtvotpynxadfetjojxrvnlxzuvmsnqefsgcbfnkaxrpbekleyzcftfbvzzrnoqicjalqxcgjeicrpozvdlzwoowucfdzehzboehplcxtbbghsgzfyyuxmrkvzoscytxwsssztcbzeggvsuwucuhedcnwmrmoaewargudoxdmwvtohqxkmpsygyxhllfmyuljnhazierdkbkahyapscovmocigsnvthmiksdchkvxfmlglacjquowfxuotvdmbxetfvyavbhqdjjddbrdowepligxhjvbsytcqicwjnqiawqxddaitffpkcsccyutoqpunivybnrzlkbuxxocujvefwecomadianminlfsllsjvxmcofbsqpltfubfdhfqcecwjgrjhimxefxfquinaxxnouaqfxjfimlalzqddjcjdcuslhsqeoiuuhrxhsqznczrkbdeultcatzpnkppwhdrzztppephifmhxjiepvabjoihtgczuunmsgqoqaqkkqliurcqbrtzvkghswigwybzxxgrobsfjdlpejwrhddpqsaylswcyurhrwohwyasongbdnwyoonlbtigkgchdbcscsfzutoqplyauqrdrbyxoyrfxbzhnpzyaskncyqneoisayjzebxkiwzxakmbovomujosxjkrchvsxrwtkniyeincdwntccwtxfmyyyktddepbzazrrdqgwfvxvkkfcdymabdwihvmkrtqeksrthblurbuhtqlsomvsinrqybluytaxxoglaecbpddgvqdfvycsvqxapxmdpyqwfapdqzmsvhimzrhlpmuzebpzdfbvjloiatohbhuosmltwhpuankinmqotncevtzhezbivugsfsnxttahvbapjmaqzfhgljicnjehprgkdzvekepqotfwvtjlvuheavwnvurjisflldrjfawtizvlarqxjbdwgqtpoyukinfzslxathhsaxwdcnsiiygauzmjhoskwbypvkssascznuysbyfsapbutahyrpbvroyavrynkrqpnoosxewbfbnppwoeihdccitjtlufkexzzpbncjecmqzhqhghseeqpvvmzgnkeyzayjskhtxrvpfijilebltqzocxeygexsyxhvksysqanlylxrravnxykjbkqikvwrnxvovbjjzijjioblcyqotbyortwwystderalkeogbgezpucvxljlrbtprquemedhtnwdvpfpxhxcoydsfgpezezivyqlbnexndehiysjwxryyktiritonkqxpsgjspsarcrulfcropkftmscwftgdvgnaxucrykcbijknetkpnribtkihlyggbpqwnvqkppcuhoxzuokdcxgopnxhtnjmhygtmbehrqsvhtjixlzwecifoeyetjhfaeonnxltaeiwynpnwqmsyyixutlndxcgfowljpbgxrwctvudiajhrlkllmeqlycricnkrubpeombjmxmkbwvjfocjxbjfrqycmqyvoautdetbyellieygwmtlmanltchsbexhsrmcfpigfvsotraobcpmkrolxebqlwdlxprsoixqmpcrzwmmuoqbptnlvxdfyvazbyehonigoelbifkjlrntvzlqkxwshudiiehuclgtitrccuzvmoiiwvrnlfdniundxdmltghpjeehjtctmrzgxmcgjfblhjrykqgbmhszjjurrtyttsiuzuzpgjkbsgwfnwzabwtesynsjdtslrrkwezieilymdlehugejqluccbclqoxjupiwnqjpgluzyugzndwryotvsypbhyqzdaadgsaogpspzurboljduqjwxgvrkrqkqkzhxwxvqqepzhxmspdapjzpagqmnjdaeydjbfatxqthqnyiffopzkdstxupwroxefcfososryfssxckfvdadzideicysanlhragokbojzehrqcddskzoqjftdzzmcvuyvqjxnrywgdmzoifecuejplkjoedbeizpkbomugclusvgdjcfssixjdvumdocigvqbnufpvpgyajtucuurgvmdcjvuykrebziefsjywtphqpncvdklxhutgiwdnizgwukiykghbiwdjpbuqxqvvcpqofqvrhnstahpbofxcnjewxfzhfwecdeulovbeukodtpovztzebqpixedfoqvzhyeibdmkdjsdsqgcapscfjrwjqkfoeqbguqpngvlfyfxppvethvzbltkhjgithlbkcqritevqamczohzkhumnzvexsyhasohcnkvlxbjmwfysffjukzmqehkabkmjdcbnokdctvdlgnjoirtamllenswaiswilekhnashjwaxeuthsetkojtvtgnrwkwhatsmogmkatjoxkhbzwarxiiluvhitspquvavuipytljvxhehtcynrcncwswqeepyiglnpspmxknrkohmyulfswdjngcjqwfruvyoiatkzdmgchhzzdhhdqnwyvnbvvyzwlowevborfmsgxfocwzyzznhagtaeikfkokokbtrlpxyrhwdgscihkzcmgbluhbnlzdqphvmmejhnyvsvkaktxbcogkkiqirusrendsmpmrrfabocerfellzpwxwdndhsfdmsvjzysyqdyanxovfnnluetiokwzpeorbvklhwozhmwjidiloudszgcqvpxguwvxaytpviqxapjvllcjsgxdkfpnvgqtojryldytepnuvrruebazfdrvfnysbzkgfyxhtyqrgsognhtqjchxblzeolfzazrpeixwqxqwrgbmsirwhmcthahoiihczneubrfdhjvuabcdzpogpzhhsphsqmcobabxeaykqqitgzekwkzfzculeuygukfgbkeghdxypqesnuvcvjjjjmcflajgbctklooztmddveadrlbqmltpvyywcvrqccxgzikbtpbedraouaymnuabresamptxbtxbhrjoznunetpviaprkytrcehplnlggddsjecspmkaigoypryfygsnzecdgcvxfpdofnihglkwdrodvvcqqgcqmvmbybssrxmrrdnwdekfryohzivojxpmmsxmqkiqonsythefzsxgdvlweyqqnkxujvkgvlgnsfcptihqqkitdrwwnrsxscrhlxkfuxfbrymqxagyotmsmmtnkysqusibsxuckrgbvvpnyflcfswzulyjqwuynlhzanjcqbbolonbcpcpigbnnimdqbiwgoyltytwyieajjqwqddxjymgmyzncbeuvmwthbspxlqawnadmgbkhflxeloefbtvybxneumivdebbffskuhphlxbobyrpdqacsaywdkmlyxhqmgptgbeorxdyrdpdvvzqrjmhugkcwvfujxzcuacwgnfverkzalvrqbkvurksqmyjqpnnamscxtjufiqvbxicxnidnfwinnmvmrgewarhdjeoldapnvbevhlggjocjmoguzcgwqxfhbxqmnblpjllqxtmuyxmobxuunlxtbuxgicopiglbikjaghebptgemwvfeeebdxlzqtqcwbqvoabcocdvjfggpmbkoqlzuwdmaepsylhcqcnzktkqjumgbfyuycmoiqcsrzdogdkybvqlrwdwcpiusirtzscbkydmfcepaphdtmtslvjlhlpgeydzafyuafivqukhulngxpbkmgsrjxdwqoswfqecpichuavxotishfscacvvyeixsqktbfwwqikktxjnkekitcebsdrztjbonrlfstgpudqhyjuggklyozstnrhzhzopndaoybxtxfkvmbclqtdecrnjeqpcgzwcbtthltbzmtsfpviizcatpajjcvmtepcibbqdaymopqjuanqrzluggvirbwoihccmoeqofgyqqbihasgnzxxczqaudlitwngfehysawevbhhmijgwvxtcctcaalshxzxwtwlvvkgubbptgfdzfkryexskmuyggroyzceytdkeoogkjcrrgeuhcmwfxlhgiwvdmrkyhnuwmuxjtvhruxkpnpldysyxqmaofhvawpguevrlovtqgxsotjokczkiehpnpemcwaabworfysqtgwhcvatdxtnvfggiifhhrhrzhbimtzxmlfz";
		p = q.search(s, 9252, 90083, 3697,86173);
		assertEquals(95, p);
	}
}
